services:
 mysql-container:
  image: mysql:latest
  environment:
   MYSQL_ROOT_PASSWORD: admin
  ports:
   - "3306:3306"
  volumes:
   - ./scripts:/docker-entrypoint-initdb.d
  networks:
   - ecom-network

  hostname: mysql-host-products-microservice
 products-microservice:
  image: sayanpr99/sayan-ecom-products-microservice:v1.0
  environment: 
   MYSQL_HOST: mysql-host-products-microservice
   MYSQL_PASSWORD: admin
  ports:
   - "8080:8080"
   - "8081:8081"
  networks:
   - ecom-network

 postgres-container:
  image: postgres:16.1
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=admin
   - POSTGRES_DB=eCommerceUsers
  ports:
   - "5432:5432"
  volumes:
   - ./postgres-scripts:/docker-entrypoint-initdb.d
  networks:
   - ecom-network

 users-microservice:
  image: sayanpr99/sayan-ecom-users-microservice:v1.0
  environment: 
   - POSTGRES_HOST=postgres-container
   - POSTGRES_PASSWORD=admin
  ports:
   - "9090:9090"
  networks:
   - ecom-network

networks:
 ecom-network:
  driver: bridge